### ISSUE TITLE
Getting error when loading the app

### ISSUE THREAD

**Issue by abhi12ravi** [Gladiator07/Text-to-image-synthesis-with-GANs#2]
Hi there, 
I'm trying to load the app on Firefox (Win 10), butI get the following error:

![image](https://user-images.githubusercontent.com/4570479/120086698-2e2bf100-c0d9-11eb-8ad3-332838a3596b.png)

Kindly help me fix the error as I'd like to try out the app. 

Cheers, 
Abhi

**Comment by Gladiator07** [comment]
Thanks for pointing out. It's fixed now. I guess there was a problem from streamlit server as it couldn't handle many requests, so it might have crashed.
