### ISSUE TITLE
The link https://share.streamlit.io/gladiator07/text-to-image-synthesis-with-attngan/main/app.py is doesn't work

### ISSUE THREAD

**Issue by dmitriypotapov19** [Gladiator07/Text-to-image-synthesis-with-GANs#3]
And when I try to run this application I have problem "OSError: cannot open resource"
How can I solve this problem ?

**Comment by dmitriypotapov19** [comment]
And when I try to run this application I have problem "OSError: cannot open resource"

**Comment by Gladiator07** [comment]
Hi, pls check now, it's working again. Thanks for pointing out.
